### ISSUE TITLE
Integrating with Unity

### ISSUE THREAD

**Issue by deltamish** [razorpay/razorpay-dot-net#15]
Hi,

As we know Unity is a very popular 3d game engine framework. Hence we are using the same to develop our project. Unity has C# .net 4.5 as  scripting backend. Our project requires user to pay through online portal and we though Razorpay would be best as its built from scratch revolving Indian market.
Hence if you can give me guidance as to how I could integrate the same . It will be highly helpful 

thanks & regards

**Comment by captn3m0** [comment]
We do not recommend integrating this SDK with Unity directly, since it is expected to be part of your backend and [include your secret credentials](https://github.com/razorpay/razorpay-dot-net#initialize).

For a game, you should instead embed a webview and use our Checkout APIs on the frontend: https://razorpay.com/docs/checkout/
